### ISSUE TITLE
MetaIssue: Address The Dumpster Fire Called "Loader.lua"

### ISSUE THREAD

**Issue by Sewerbird** [Sewerbird/Helios2400#10]
I've kicked the can down the road just a smidgeon too long on making factory classes and load states: all initialization code right now lives in Loader.lua, with not a factory class or abstraction in sight. This needs to be factored out in a respectable way.

## Issues to Create

- [x] [Implement an Asset Loader (with JSON datasheet)](https://github.com/Sewerbird/Helios2400/issues/23)
- [x] [Create a Save/Serialization Format with Loader/Unloader](https://github.com/Sewerbird/Helios2400/issues/24)
- [x] [Make factory classes for common GameObjects (tiles, units, cities, ...)](https://github.com/Sewerbird/Helios2400/issues/25)
- [x] [Implement Rudimentary UI](https://github.com/Sewerbird/Helios2400/issues/26)

**Comment by Sewerbird** [comment]
Loader is no longer a dumpster fire!
